package tenant

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
)

// bootstrapYAMLTemplate is the file written by WriteBootstrapFile.
// It creates exactly one operator-role entry for the given UID and name.
const bootstrapYAMLTemplate = `# aimux tenants.yaml — generated by --bootstrap-operator-uid
# Edit this file to enroll additional tenants; send SIGHUP to reload.
tenants:
  - name: operator
    uid: %d
    role: operator
    rate_limit_per_sec: 1000
    max_concurrent_sessions: 10
    log_retention_days: 90
    removal_drain_seconds: 30
`

// WriteBootstrapFile creates the initial tenants.yaml at path with a single
// operator-role entry for uid.
//
// Idempotency contract:
//   - If path already exists (even if empty), the function is a no-op: it logs a
//     message and returns nil without modifying the file.
//   - If path is absent, the file is created with mode 0600 and contains exactly
//     one operator entry for uid.
//
// The written file is validated via LoadFromFile before returning to ensure it
// can be parsed successfully on the next daemon start.
func WriteBootstrapFile(path string, uid int) error {
	// Check for existing file (even empty counts as "exists").
	if _, err := os.Stat(path); err == nil {
		// File exists — count entries for the log message.
		snap, loadErr := LoadFromFile(path)
		count := 0
		if loadErr == nil && snap != nil {
			count = len(snap.byUID)
		}
		log.Printf("tenant bootstrap: %q exists with %d entries; bootstrap skipped", path, count)
		return nil
	}

	// Ensure parent directory exists.
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("WriteBootstrapFile: create parent dir: %w", err)
	}

	content := fmt.Sprintf(bootstrapYAMLTemplate, uid)

	// Write atomically via temp file in the same directory to avoid partial writes.
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".tenants-bootstrap-*.yaml")
	if err != nil {
		return fmt.Errorf("WriteBootstrapFile: create temp: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("WriteBootstrapFile: write temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("WriteBootstrapFile: close temp: %w", err)
	}
	if err := os.Chmod(tmpPath, 0o600); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("WriteBootstrapFile: chmod temp: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("WriteBootstrapFile: rename to %q: %w", path, err)
	}

	// Self-validate: ensure the written file parses correctly.
	if _, err := LoadFromFile(path); err != nil {
		// The file was written but is invalid — remove it to avoid a broken state.
		_ = os.Remove(path)
		return fmt.Errorf("WriteBootstrapFile: self-validation failed: %w", err)
	}

	log.Printf("tenant bootstrap: created %q with operator entry for uid %d", path, uid)
	return nil
}
